/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.softeq.gradle.itest


import org.gradle.testfixtures.ProjectBuilder
import spock.lang.Specification

class ItestPluginTest extends Specification {

    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()
        project.plugins.apply('java')

        when:
        project.plugins.apply('com.softeq.gradle.itest')

        then:
        def task = project.tasks.findByName('integrationTest')
        assert task.group == 'verification'
        assert task.mustRunAfter.mutableValues[0] == 'test'
    }

    def "plugin registers task (verify up to date option)"() {
        given:
        def project = ProjectBuilder.builder().build()
        project.plugins.apply('java')

        when:
        project.plugins.apply('com.softeq.gradle.itest')

        then:
        def task = project.tasks.findByName('integrationTest')
        def upToDateClosure = task.outputs.properties['upToDateSpec']['specs'][0].closure
        assert !upToDateClosure()
    }

}
